apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: assets-monitoring
  namespace: watchn
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      name: assets
  endpoints:
    - interval: 5s
      path: /metrics
      port: "8080"
  namespaceSelector:
    matchNames:
      - "default"

